<a href="https://colab.research.google.com/github/weilainicolas/DEX-Arbitrage/blob/main/pytorch/00_pytorch_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
#2. Create a random tensor with shape (7, 7).
rand=torch.rand(7,7)
rand

tensor([[0.5792, 0.8412, 0.3031, 0.0437, 0.2285, 0.9577, 0.9342],
        [0.0778, 0.8545, 0.1215, 0.8301, 0.7980, 0.9606, 0.4911],
        [0.3700, 0.7959, 0.4724, 0.6298, 0.0831, 0.9201, 0.6986],
        [0.6259, 0.5021, 0.0198, 0.2698, 0.6569, 0.7723, 0.0069],
        [0.2009, 0.5420, 0.0769, 0.0963, 0.1098, 0.0328, 0.7262],
        [0.2035, 0.4991, 0.0524, 0.0128, 0.7962, 0.9415, 0.4598],
        [0.3882, 0.3583, 0.9407, 0.3449, 0.3257, 0.9803, 0.7322]])

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).


In [3]:
tensor_1=torch.rand(1,7)

In [7]:
rand @ tensor_1.T

tensor([[2.2518],
        [2.2577],
        [2.4161],
        [1.4427],
        [1.1693],
        [1.4627],
        [2.5622]])

4. Set the random seed to 0 and do 2 & 3 over again.

In [13]:
seed=0
torch.manual_seed(0)
tensor_1=torch.rand(7,7)
tensor_2=torch.rand(1,7)
print(tensor_1)
print(tensor_2)
print(tensor_1 @ tensor_2.T)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])
tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [3]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)

6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:


In [3]:
torch.manual_seed(1234)
x_1=torch.rand(2,3)
x_2=torch.rand(2,3)
x_g_1=x_1.to('cuda')
x_g_2=x_2.to('cuda')

In [4]:
print(x_g_1)
print(x_g_2)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')


In [6]:
result=x_g_1 @ x_g_2.T

8. Find the maximum and minimum values of the output of 7.

In [9]:
print(result.max())
print(result.min())


tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


9. Find the maximum and minimum index values of the output of 7.

In [10]:
print(torch.argmax(result))
print(torch.argmin(result))

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')


10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [15]:
torch.manual_seed(7)
tensor=torch.rand(1,1,1,10)
tensor_squeeze=tensor.squeeze()
print(tensor, tensor.shape)
print(tensor_squeeze,tensor_squeeze.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])


In [13]:
tensor.shape

torch.Size([1, 1, 1, 10])